// <auto-generated />
namespace DonorGateway.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MailerReason : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MailerReason));
        
        string IMigrationMetadata.Id
        {
            get { return "201606131427118_Mailer-Reason"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
